blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Help & Questions
    url: https://community.auth0.com
    about: Ask general support or usage questions in the Auth0 Community forums
  - name: ðŸ“‘ FAQ
    url: https://github.com/auth0/ui-components-ios/blob/master/FAQ.md
    about: Check some commonly asked questions
  - name: ðŸš€ Common Tasks
    url: https://github.com/auth0/ui-components-ios#common-tasks
    about: Check the Common Tasks section of the README to get up to speed with ui-components-ios
  - name: ðŸ“– API Documentation
    url: https://auth0.github.io/ui-components-ios/documentation/auth0
    about: Check the public API documentation for in-depth overview of all the available features
