name: SCA

on:
  pull_request:
      types:
        - opened
        - synchronize

jobs:
  snyk-cli:
    uses: auth0/devsecops-tooling/.github/workflows/sca-scan.yml@main
    with:
      additional-arguments: "--exclude=README.md"
    secrets: inherit
